PG_CONNECTION_STRING: str = 'postgresql://postgres@localhost/postgres'
PG_POOL: str = 'pg_pool'
REDIS_CONNECTION_STRING: str = 'redis://localhost'
REDIS_CONNECTION: str = 'redis_connection'
SESSION: str = 'session'
ONE_MINUTE = 60
ONE_HOUR = ONE_MINUTE * 60
ONE_DAY = 24 * ONE_HOUR
SEVEN_DAYS = ONE_DAY * 7
CACHE_EXPIRE_TIME = ONE_MINUTE
